Repository Senity-Waved/Waved_FE, pull requests merged in 2024-03, with the labels that each got.

#7 [#5][FEATURE] 공통 컴포넌트 (헤더, 푸터) 마크업 및 스타일링
  public/icons/icon-home-filled.svg
  public/icons/icon-home-normal.svg
  public/icons/icon-left-arrow.svg
  public/icons/icon-mychallenge-filled.svg
  public/icons/icon-mychallenge-normal.svg
  public/icons/icon-notification.svg
  public/icons/icon-profile-filled.svg
  public/icons/icon-profile-normal.svg
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/pages/index.tsx
Labels: 🎨 style

#8 [#6][FEATURE] 공통 컴포넌트 (버튼, 탭) 마크업 및 스타일링
  package-lock.json
  package.json
  src/components/common/BottomFixedBtn.tsx
  src/components/common/Btn.tsx
  src/components/common/TabMenu.tsx
  src/pages/index.tsx
Labels: 🎨 style

#10 [#9][FEATURE] Modal Portal 설정 및 Modal 컴포넌트 생성
  src/components/modal/Modal.tsx
  src/components/modal/ModalPortal.tsx
  src/components/modal/ModalTest.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
Labels: ✨ feat

#12 [#11][FEATURE] 공통 레이아웃 설계 및 예시 페이지 분리
  src/components/common/BottomFixedBtn.tsx
  src/components/common/Btn.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/Layout.tsx
  src/components/common/TabMenu.tsx
  src/components/modal/Modal.tsx
  src/pages/example/index.tsx
  src/pages/index.tsx
  src/styles/global.ts
Labels: 🎨 style

#16 [#13][FEATURE] 마이챌린지 페이지 마크업 및 스타일링
  public/icons/icon-empty-character.svg
  public/icons/icon-pointer-blue.svg
  public/icons/icon-pointer-gray.svg
  src/components/common/EmptyView.tsx
  src/components/common/Footer.tsx
  src/components/common/TabMenu.tsx
  src/components/mychallenge/ChallengeBtn.tsx
  src/components/mychallenge/ChallengeEmptyView.tsx
  src/components/mychallenge/ChallengeItem.tsx
  src/components/mychallenge/ChallengeProgress.tsx
  src/components/mychallenge/ChallengeSection.tsx
  src/pages/mychallenge/index.tsx
Labels: 🎨 style

#21 [#19][FEATURE] 공통 컴포넌트 (헤더, 푸터) 동적 스타일링 및 props 정리
  public/icons/index.ts
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/Layout.tsx
  src/pages/example/index.tsx
  src/pages/profile/index.tsx
Labels: ✨ feat, 🎨 style

#18 [#1][FEATURE] 회원가입 / 로그인 페이지 마크업 및 스타일링
  package-lock.json
  package.json
  public/icons/icon-checkbox-checked.svg
  public/icons/icon-checkbox-not-checked.svg
  public/icons/icon-down-arrow.svg
  public/icons/icon-google-logo.svg
  public/icons/icon-small-arrow.svg
  public/images/image-fanfare.svg
  public/images/image-waved-preview1.svg
  public/images/image-waved-preview2.svg
  public/images/image-waved-preview3.svg
  src/components/common/Header.tsx
  src/components/common/Layout.tsx
  src/components/modal/ModalTest.tsx
  src/components/onboarding/PreviewSlider.tsx
  src/components/register/JobTitleInput.tsx
  src/components/register/NicknameInput.tsx
  src/components/register/PrivacyInput.tsx
  src/components/register/ServiceTermCheck.tsx
  src/constants/jobTitle.ts
  src/constants/years.ts
  src/pages/onboarding/index.tsx
  src/pages/register/index.tsx
  src/pages/register/success/index.tsx
  src/types/gender.ts
  src/types/register.ts
Labels: ✨ feat, 🎨 style

#25 [#15][FEATURE] 챌린지 상세 정보 마크업 및 스타일링
  public/icons/icon-participant-black.svg
  public/icons/icon-participant-white.svg
  public/icons/icon-share.svg
  src/components/challenge/ChallengeHeader.tsx
  src/components/challenge/ChallengeReviewItem.tsx
  src/components/challenge/ChallengeSummary.tsx
  src/components/challenge/ShareBtn.tsx
  src/components/common/EmptyView.tsx
  src/components/common/Header.tsx
  src/components/common/TabMenu.tsx
  src/constants/emptyText.ts
  src/pages/challenge/[id].tsx
Labels: ✨ feat, 🎨 style

#26 [#17][FEATURE] 챌린지 인증 페이지 마크업 및 스타일링
  public/icons/icon-photo-delete.svg
  public/icons/icon-photo-upload.svg
  public/icons/icon-pointer-gray.svg
  src/components/common/TextArea.tsx
  src/components/common/WriteLayout.tsx
  src/components/modal/Modal.tsx
  src/components/mychallenge/ChallengeBtn.tsx
  src/components/mychallenge/ChallengeItem.tsx
  src/components/mychallenge/ChallengeProgress.tsx
  src/components/mychallenge/ChallengeSection.tsx
  src/components/verification/PhotoInput.tsx
  src/constants/challengeSectionText.ts
  src/constants/regex.ts
  src/constants/writeLayoutText.ts
  src/pages/verification/history/[challengeid].tsx
  src/pages/verification/post/[challengeid].tsx
Labels: ✨ feat, 🎨 style

#29 [#2][FEATURE] 프로필 페이지 마크업 및 스타일링
  public/icons/icon-github-logo.svg
  public/icons/icon-question.svg
  src/components/profile/DepositItem.tsx
  src/components/profile/ProfileShortcut.tsx
  src/components/register/JobTitleInput.tsx
  src/components/register/NicknameInput.tsx
  src/components/register/PrivacyInput.tsx
  src/components/register/ServiceTermCheck.tsx
  src/constants/profileSnackBarText.ts
  src/pages/onboarding/index.tsx
  src/pages/profile/edit/index.tsx
  src/pages/profile/index.tsx
  src/pages/profile/mydeposit/index.tsx
  src/pages/profile/mygithub/index.tsx
  src/pages/register/index.tsx
  src/types/register.ts
  src/types/snackbar.ts
  src/utils/changePriceFormat.ts
Labels: ✨ feat, 🎨 style

#32 [#4][FEATURE] 챌린지 참여 신청 페이지 마크업 및 스타일링
  package-lock.json
  package.json
  public/icons/icon-done.svg
  public/icons/icon-list.svg
  src/atoms/selectedChallenge.ts
  src/components/challenge/ChallengeSummary.tsx
  src/components/challenge/participant/DepositGuide.tsx
  src/components/challenge/participant/DepositRefundGuide.tsx
  src/components/common/BottomFixedBtn.tsx
  src/components/register/JobTitleInput.tsx
  src/components/register/NicknameInput.tsx
  src/components/register/PrivacyInput.tsx
  src/components/register/ServiceTermCheck.tsx
  src/constants/payment.ts
  src/pages/challenge/[id].tsx
  src/pages/challenge/participant/index.tsx
  src/pages/challenge/participant/success/index.tsx
  src/pages/profile/edit/index.tsx
  src/pages/register/index.tsx
  src/types/gender.ts
  src/types/register.ts
  src/types/selectedChallenge.ts
Labels: 🎨 style

#35 [#20][FEATURE] 챌린지 인증내역 페이지 마크업 및 스타일링
  public/icons/icon-heart-black-filled.svg
  public/icons/icon-heart-black.svg
  public/icons/icon-heart-white-filled.svg
  public/icons/icon-heart-white.svg
  public/icons/icon-link.svg
  public/icons/icon-pointer-blue.svg
  public/icons/icon-stamp-bad.svg
  public/icons/icon-stamp-default.svg
  public/icons/icon-stamp-good.svg
  src/components/common/Header.tsx
  src/components/common/TabMenu.tsx
  src/components/modal/Modal.tsx
  src/components/mychallenge/ChallengeBtn.tsx
  src/components/mychallenge/ChallengeItem.tsx
  src/components/mychallenge/ChallengeProgress.tsx
  src/components/mychallenge/ChallengeSection.tsx
  src/components/verification/collection/Stamp.tsx
  src/components/verification/collection/VerificationItem.tsx
  src/components/verification/collection/VerificationList.tsx
  src/components/verification/collection/VerificationPhotoItem.tsx
  src/components/verification/post/PhotoInput.tsx
  src/constants/challengeSectionText.ts
  src/constants/day.ts
  src/pages/mychallenge/index.tsx
  src/pages/verification/collection/[challengeid].tsx
  src/pages/verification/history/[challengeid].tsx
  src/pages/verification/post/[challengeid].tsx
  src/types/verification.ts
  src/utils/calculateDDay.ts
  src/utils/parseDate.ts
Labels: ✨ feat, 🎨 style

#36 [#27][FEATURE] 챌린지 목록/상세 디자인 변경 사항 적용 및 기능 구현
  package-lock.json
  package.json
  public/icons/icon-alarm-active.svg
  public/icons/icon-waved-logo.svg
  src/components/challenge/ChallengeHeader.tsx
  src/components/challenge/ChallengeSummary.tsx
  src/components/challenge/ShareBtn.tsx
  src/components/common/ScrollXBox.tsx
  src/components/common/SnackBar.tsx
  src/components/home/ChallengeCard.tsx
  src/components/home/ChallengeCardWide.tsx
  src/components/home/FloatingBtn.tsx
  src/components/home/HomeHeader.tsx
  src/components/home/RecruitingChallenge.tsx
  src/components/home/RecrutingList.tsx
  src/components/home/TopBanner.tsx
  src/constants/homeSectionTitle.ts
  src/constants/verificationType.ts
  src/pages/api/myProcessingChallenge.ts
  src/pages/api/recruitingChallenge.ts
  src/pages/challenge/[challengeGroupId].tsx
  src/pages/challenge/participant/index.tsx
  src/pages/index.tsx
  src/types/challengeList.ts
  src/types/myProcessingChallenge.ts
  src/types/recruitingChallenge.ts
Labels: ✨ feat, 🎨 style, 🔨 refactor

#41 [#40][FEATURE] 수정 사항 반영 및 공통 코드와 리코일 추가
  public/images/image-waved-preview1.svg
  public/images/image-waved-preview2.svg
  public/images/image-waved-preview3.svg
  src/components/home/FloatingBtn.tsx
  src/components/register/PrivacyInput.tsx
  src/pages/challenge/participant/index.tsx
  src/pages/challenge/participant/success/index.tsx
  src/pages/onboarding/index.tsx
  src/pages/register/index.tsx
  src/pages/register/success/index.tsx
Labels: ✨ feat, 🎨 style

#42 [#38][FEATURE] 모바일 친화적인 레이아웃을 위한 스타일링 수정
  src/components/challenge/ChallengeSummary.tsx
  src/components/common/BottomFixedBtn.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/Layout.tsx
  src/components/common/SnackBar.tsx
  src/components/common/TabMenu.tsx
  src/components/home/FloatingBtn.tsx
  src/components/mychallenge/ChallengeSection.tsx
  src/pages/404.tsx
  src/pages/challenge/[challengeGroupId].tsx
  src/pages/challenge/participant/index.tsx
  src/pages/challenge/participant/success/index.tsx
  src/pages/challenge/request/success/index.tsx
  src/pages/onboarding/index.tsx
  src/pages/profile/edit/index.tsx
  src/pages/profile/mygithub/index.tsx
  src/pages/register/index.tsx
  src/pages/register/success/index.tsx
  src/styles/global.ts
Labels: 🎨 style, 🔨 refactor

#47 [TEST] JWT 관리 및 Axios 테스트
  .gitignore
  package-lock.json
  package.json
  src/lib/axios/instance.ts
  src/lib/axios/interceptors.ts
  src/lib/axios/profile/api.ts
  src/middleware.ts
  src/pages/api/auth/logout.ts
  src/pages/api/auth/reissue.ts
  src/pages/api/auth/session.ts
  src/pages/api/test/login.ts
  src/pages/api/test/reissue.ts
  src/pages/index.tsx
  src/pages/logintest/index.tsx
  src/pages/oauth/index.tsx
  src/pages/profile/index.tsx
  src/pages/register/index.tsx
  src/types/auth.ts
  src/types/gender.ts
  src/utils/cookie.ts
Labels: ✨ feat, ✅ test

#48 [#39][FEATURE] 로그인 API 연동 및 JWT 관리, Axios 설정
  src/components/home/FloatingBtn.tsx
  src/pages/index.tsx
  src/pages/oauth/index.tsx
  src/pages/onboarding/index.tsx
  src/pages/profile/index.tsx
  src/utils/cookie.ts
Labels: ✨ feat

#45 [#31][FEATURE] 마이챌린지/인증하기/인증내역 페이지 디자인 변경 사항 반영
  package-lock.json
  src/components/common/Btn.tsx
  src/components/common/EmptyView.tsx
  src/components/common/WriteLayout.tsx
  src/components/modal/Modal.tsx
  src/components/mychallenge/ChallengeBtn.tsx
  src/components/mychallenge/ChallengeItem.tsx
  src/components/mychallenge/ChallengeProgress.tsx
  src/components/mychallenge/ChallengeSection.tsx
  src/components/verification/collection/Stamp.tsx
  src/components/verification/collection/VerificationItem.tsx
  src/components/verification/collection/VerificationList.tsx
  src/components/verification/collection/VerificationPhotoItem.tsx
  src/components/verification/post/LinkInput.tsx
  src/components/verification/post/PhotoInput.tsx
  src/constants/challengeSectionText.ts
  src/constants/regex.ts
  src/constants/verificationType.ts
  src/constants/writeLayoutText.ts
  src/pages/mychallenge/index.tsx
  src/pages/verification/collection/[groupId].tsx
  src/pages/verification/post/[challengeid].tsx
  src/pages/verification/post/[groupId].tsx
  src/types/myChallenge.ts
  src/types/verification.ts
  src/utils/calculateDDay.ts
  src/utils/parseDate.ts
Labels: ✨ feat, 🎨 style, 🔨 refactor

#51 [#50][FEATURE] 마이챌린지 진행완료 섹션 디자인 수정사항 반영
  src/atoms/modal.ts
  src/components/common/Btn.tsx
  src/components/common/WriteLayout.tsx
  src/components/modal/Modal.tsx
  src/components/modal/ModalTest.tsx
  src/components/mychallenge/ChallengeBtn.tsx
  src/components/mychallenge/ChallengeItem.tsx
  src/components/mychallenge/ChallengeLabel.tsx
  src/components/mychallenge/ChallengeProgress.tsx
  src/components/profile/myreview/MyReviewItem.tsx
  src/components/verification/collection/Stamp.tsx
  src/hooks/useModal.ts
  src/pages/mychallenge/index.tsx
  src/pages/profile/index.tsx
  src/pages/profile/mygithub/index.tsx
  src/pages/profile/myreview/index.tsx
  src/pages/verification/collection/[groupId].tsx
  src/pages/verification/post/[groupId].tsx
  src/types/modal.ts
  src/types/myChallenge.ts
Labels: ✨ feat, 🎨 style

#54 [#53][FEATURE] 챌린지 신청 기능 구현 (결제 제외)
  src/lib/axios/challengeRequest/api.ts
  src/pages/challenge/participant/index.tsx
Labels: ✨ feat

#56 [#55][FEATURE] 홈 및 챌린지 상세 디자인 변동사항 반영 및 이미지 렌더링
  public/icons/icon-notification.svg
  public/images/image-challenge-backend.png
  public/images/image-challenge-frontend.png
  public/images/image-challenge-github.png
  public/images/image-challenge-nottodo.png
  public/images/image-waved-banner1.png
  public/images/image-waved-banner2.png
  public/images/image-waved-banner3.png
  src/components/challenge/VerificationExample.tsx
  src/components/home/ChallengeCard.tsx
  src/components/home/ChallengeCardWide.tsx
  src/components/home/HomeHeader.tsx
  src/components/home/TopBanner.tsx
  src/pages/challenge/[groupId].tsx
  src/utils/getChallengeThumbnailPath.ts
Labels: ✨ feat, 🎨 style

#59 [#44][FEATURE] 포트원 결제 API 구현 및 챌린지 참가신청 구현
  package-lock.json
  src/lib/axios/challengeRequest/api.ts
  src/lib/axios/instance.ts
  src/lib/axios/profile/api.ts
  src/lib/portone/requestPay.ts
  src/pages/_document.tsx
  src/pages/challenge/participant/index.tsx
  src/types/portone.d.ts
  src/types/profile.ts
Labels: ✨ feat

#60 [#49][FEATURE] 프로필 조회 및 수정 API 연동
  src/components/profile/ProfileShortcut.tsx
  src/components/register/JobTitleInput.tsx
  src/components/register/PrivacyInput.tsx
  src/constants/jobTitle.ts
  src/lib/axios/profile/api.ts
  src/pages/api/auth/unregister.ts
  src/pages/index.tsx
  src/pages/profile/edit/index.tsx
  src/pages/profile/index.tsx
  src/pages/register/index.tsx
  src/types/profile.ts
Labels: ✨ feat

#61 [#58][FEATURE] 챌린지 정보 API 연동
  src/components/challenge/ChallengeReviewItem.tsx
  src/components/home/ChallengeCardWide.tsx
  src/components/home/RecruitingChallenge.tsx
  src/pages/api/myProcessingChallenge.ts
  src/pages/api/recruitingChallenge.ts
  src/pages/challenge/[groupId].tsx
  src/pages/index.tsx
  src/types/challengeGroup.ts
  src/types/myProcessingChallenge.ts
  src/types/recruitingChallenge.ts
  src/types/review.ts
Labels: ✨ feat

#63 [#46][FEATURE] 마이챌린지/인증하기 API 연동
  package-lock.json
  src/components/common/WriteLayout.tsx
  src/components/modal/ModalTest.tsx
  src/components/mychallenge/ChallengeBtn.tsx
  src/components/mychallenge/ChallengeItem.tsx
  src/components/mychallenge/ChallengeLabel.tsx
  src/components/mychallenge/ChallengeSection.tsx
  src/lib/axios/instance.ts
  src/lib/axios/mychallenge/api.ts
  src/lib/axios/verification/api.ts
  src/pages/mychallenge/index.tsx
  src/pages/verification/collection/[challengeGroupId].tsx
  src/pages/verification/post/[challengeGroupId].tsx
  src/types/myChallenge.ts
Labels: ✨ feat

#68 [#57][FEATURE] 서버용 axios 인스턴스 생성 및 인터셉터 설정
  src/lib/axios/axiosConfig.ts
  src/lib/axios/instance.ts
  src/lib/axios/interceptors.ts
  src/lib/axios/serverInstance.ts
  src/pages/api/auth/server/reissue.ts
  src/pages/profile/index.tsx
Labels: ✨ feat

#66 [#62][FEATURE] 깃허브 연동 관련 API 연동, 깃허브 연동 기능 구현
  src/lib/axios/profile/api.ts
  src/pages/profile/mygithub/index.tsx
  src/types/github.ts
Labels: ✨ feat

#69 [#58][FEATURE] 챌린지 정보 API 연동 2차
  src/components/challenge/ChallengeReviewItem.tsx
  src/components/challenge/ChallengeSummary.tsx
  src/components/challenge/ParticipantButton.tsx
  src/components/common/BottomFixedBtn.tsx
  src/constants/weekdays.ts
  src/lib/axios/challenge/api.ts
  src/lib/axios/home/api.ts
  src/pages/challenge/[groupId].tsx
  src/pages/index.tsx
  src/types/challengeGroup.ts
  src/types/jobTitle.ts
  src/types/recruitingChallenge.ts
  src/types/review.ts
  src/types/selectedChallenge.ts
Labels: ✨ feat

#71 [#70][FEATURE] 피그마 수정사항 및 디자인 QA 결과 반영
  public/images/image-waved-preview1.png
  public/images/image-waved-preview1.svg
  public/images/image-waved-preview2.png
  public/images/image-waved-preview2.svg
  public/images/image-waved-preview3.png
  public/images/image-waved-preview3.svg
  src/components/challenge/participant/DepositRefundGuide.tsx
  src/components/onboarding/PreviewSlider.tsx
  src/pages/challenge/participant/index.tsx
  src/pages/onboarding/index.tsx
  src/pages/register/index.tsx
Labels: 🎨 style

#73 [#65][FEATURE] 챌린지 후기 기능 구현 및 나의 후기 API 연동
  package-lock.json
  package.json
  src/components/challenge/ChallengeReviewItem.tsx
  src/components/challenge/ParticipantButton.tsx
  src/components/mychallenge/ChallengeBtn.tsx
  src/components/profile/myreview/MyReviewItem.tsx
  src/lib/axios/challenge/api.ts
  src/lib/axios/review/api.ts
  src/pages/challenge/[groupId].tsx
  src/pages/mychallenge/review/[myChallengeId].tsx
  src/pages/profile/myreview/edit/index.tsx
  src/pages/profile/myreview/index.tsx
  src/types/review.ts
  src/utils/formattedFormText.ts
Labels: ✨ feat

#74 [#64][FEATURE] 인증내역 API 연동
  next.config.mjs
  public/icons/icon-stamp-good.svg
  src/components/common/EmptyView.tsx
  src/components/mychallenge/ChallengeBtn.tsx
  src/components/mychallenge/ChallengeItem.tsx
  src/components/mychallenge/ChallengeSection.tsx
  src/components/verification/collection/VerificationItem.tsx
  src/components/verification/collection/VerificationList.tsx
  src/components/verification/collection/VerificationPhotoItem.tsx
  src/constants/emptyText.ts
  src/hooks/useModal.ts
  src/lib/axios/mychallenge/api.ts
  src/lib/axios/verification/collection/api.ts
  src/lib/axios/verification/post/api.ts
  src/pages/mychallenge/index.tsx
  src/pages/verification/collection/[challengeGroupId].tsx
  src/pages/verification/post/[challengeGroupId].tsx
  src/types/verification.ts
Labels: ✨ feat

#78 [#75][FEATURE] 챌린지 신청 취소 API 연동
  src/components/challenge/ParticipantButton.tsx
  src/lib/axios/challenge/api.ts
Labels: ✨ feat

#80 [#76][REFACTOR] 깃헙인증제출 후 동작 로직 변경 작업
  public/icons/icon-empty-github.svg
  src/components/common/EmptyView.tsx
  src/components/mychallenge/ChallengeBtn.tsx
  src/components/verification/collection/VerificationList.tsx
  src/constants/emptyText.ts
  src/lib/axios/verification/collection/api.ts
  src/pages/mychallenge/index.tsx
  src/pages/verification/collection/[challengeGroupId].tsx
  src/pages/verification/post/[challengeGroupId].tsx
Labels: 🚨 fix, 🔨 refactor

#82 [#72][FEATURE] 관리자 페이지 생성 및 관리자 기능 구현
  src/lib/axios/admin/api.ts
  src/lib/axios/adminInstance.ts
  src/pages/admin/index.tsx
Labels: ✨ feat, 🎨 style

#83 [#72][FEATURE] 관리자 페이지 생성 및 관리자 기능 구현
  src/lib/axios/adminInstance.ts
  src/pages/admin/index.tsx
Labels: ✨ feat

#86 [#84][REFACTOR] 디자인 수정사항 반영 및 외부 경로 추가
  public/icons/icon-500-error.svg
  src/components/home/FloatingBtn.tsx
  src/components/home/TopBanner.tsx
  src/components/register/ServiceTermCheck.tsx
  src/lib/axios/profile/api.ts
  src/pages/500.tsx
  src/pages/challenge/[groupId].tsx
  src/pages/index.tsx
  src/pages/profile/index.tsx
  src/pages/profile/mygithub/index.tsx
Labels: 🎨 style, 🔨 refactor

#85 [#77][FEATURE] Axios interceptor 에러 핸들링 SnackBar
  src/atoms/snackBar.ts
  src/hooks/useSnackBar.ts
  src/lib/axios/ClientErrorSnackBar.ts
  src/lib/axios/serverErrorCatch.ts
  src/pages/_app.tsx
  src/pages/mychallenge/index.tsx
  src/pages/verification/collection/[challengeGroupId].tsx
  src/pages/verification/post/[challengeGroupId].tsx
Labels: ✨ feat
