Repository Senity-Waved/Waved_FE, pull requests merged in 2024-04, with the labels that each got.

#93 [#91][REFACTOR] 관리자 페이지 스타일링 및 코드 개선
  src/lib/axios/adminInstance.ts
  src/lib/axios/instance.ts
  src/lib/axios/serverInstance.ts
  src/lib/portone/requestPay.ts
  src/middleware.ts
  src/pages/admin/index.tsx
  src/pages/api/auth/logout.ts
  src/pages/api/auth/reissue.ts
  src/pages/api/auth/server/reissue.ts
  src/pages/api/auth/session.ts
  src/pages/api/auth/unregister.ts
  src/pages/challenge/participant/index.tsx
  src/pages/challenge/process/index.tsx
  src/pages/home/index.tsx
  src/pages/index.tsx
  src/pages/oauth/index.tsx
  src/pages/profile/mygithub/index.tsx
Labels: 🎨 style, 🔨 refactor

#94 [#89][REFACTOR] 홈 및 챌린지 상세 페이지 기능 추가 및 코드 개선
  package-lock.json
  package.json
  src/components/challenge/ChallengeHeader.tsx
  src/components/challenge/ChallengeReview.tsx
  src/components/challenge/ParticipantButton.tsx
  src/components/challenge/VerificationExample.tsx
  src/components/common/ScrollXBox.tsx
  src/components/common/TabMenu.tsx
  src/components/home/ProcessingChallenge.tsx
  src/components/home/ProcessingChallengeCard.tsx
  src/components/home/RecruitingChallenge.tsx
  src/components/home/RecruitingChallengeCard.tsx
  src/constants/challengeImagePaths.ts
  src/hooks/useHorizontalScroll.ts
  src/hooks/useSnackBar.ts
  src/lib/axios/challenge/api.ts
  src/pages/challenge/[groupId].tsx
  src/pages/home/index.tsx
  src/utils/getChallengeImagePath.ts
  src/utils/getChallengeThumbnailPath.ts
  src/utils/parseChallengeTitle.ts
  src/utils/throttle.ts
Labels: 🚨 fix, ✨ feat, 🔨 refactor

#97 [#95][FEATURE] 알림 화면 구현 및 API 연동
  package-lock.json
  package.json
  public/icons/icon-notification-on.svg
  public/icons/icon-notification.svg
  src/components/home/HomeHeader.tsx
  src/components/home/Notification.tsx
  src/lib/axios/instance.ts
  src/lib/axios/notification/api.ts
  src/pages/api/auth/token-expiry.ts
  src/pages/home/index.tsx
  src/pages/notification/index.tsx
  src/types/notify.ts
Labels: ✨ feat

#98 [#96][FEATURE] PWA 적용
  .eslintrc.json
  .gitignore
  next.config.mjs
  package-lock.json
  package.json
  public/manifest.json
  public/manifest/icon_x128.png
  public/manifest/icon_x144.png
  public/manifest/icon_x192.png
  public/manifest/icon_x48.png
  public/manifest/icon_x512.png
  public/manifest/icon_x72.png
  public/manifest/icon_x96.png
  src/pages/_document.tsx
Labels: ✨ feat

#103 [#100][BUG] 배포 환경에서 발생하는 문제 해결
  .github/workflows/develop_waved-fe.yml
  .gitignore
  next.config.mjs
  public/icons/icon-mychallenge-disabled.svg
  public/icons/index.ts
  src/components/common/Footer.tsx
  src/components/common/Layout.tsx
  src/pages/home/index.tsx
  src/pages/mychallenge/index.tsx
  src/pages/profile/index.tsx
Labels: 🚨 fix

#105 [#88][REFACTOR] 인증내역 페이지 코드개선 및 스타일오류 수정
  src/components/verification/collection/VerificationItem.tsx
  src/components/verification/collection/VerificationList.tsx
  src/components/verification/collection/VerificationPhotoItem.tsx
  src/lib/axios/verification/collection/api.ts
  src/lib/axios/verification/post/api.ts
  src/pages/verification/collection/[challengeGroupId].tsx
  src/pages/verification/post/[challengeGroupId].tsx
  src/types/verification.ts
Labels: 🎨 style, 🔨 refactor

#108 [🌊 DEPLOY] 인증 내역 수정 사항 및 refreshToken 에러 핸들링 배포 버전에 반영
  src/components/verification/collection/VerificationItem.tsx
  src/components/verification/collection/VerificationList.tsx
  src/components/verification/collection/VerificationPhotoItem.tsx
  src/lib/axios/serverInstance.ts
  src/lib/axios/verification/collection/api.ts
  src/lib/axios/verification/post/api.ts
  src/pages/api/auth/reissue.ts
  src/pages/home/index.tsx
  src/pages/profile/index.tsx
  src/pages/verification/collection/[challengeGroupId].tsx
  src/pages/verification/post/[challengeGroupId].tsx
  src/types/verification.ts
Labels: 🌊 deploy

#110 [#102][FEATURE] 특정 알림 삭제 기능 구현 및 실시간 알림 테스트
  src/components/common/EmptyView.tsx
  src/components/home/Notification.tsx
  src/components/notification/NotificationBox.tsx
  src/components/notification/NotificationModal.tsx
  src/constants/emptyText.ts
  src/lib/axios/notification/api.ts
  src/pages/home/index.tsx
  src/pages/notification/index.tsx
  src/types/notify.ts
Labels: ✨ feat

#111 [#109][FEATURE] 구글 애널리틱스(GA) 도입
  package-lock.json
  package.json
  src/lib/ga/gtag.ts
  src/pages/_app.tsx
Labels: ✨ feat

#113 [#107][FEATURE] 챌린지 홈 & 상세 페이지 수정 사항 반영
  public/icons/icon-waved-logo.svg
  public/images/image-challenge-backend.png
  public/images/image-challenge-frontend.png
  public/images/image-challenge-github.png
  public/images/image-challenge-nottodo.png
  public/images/image-verification-apply-jobkorea.png
  public/images/image-verification-apply-jumpfit.png
  public/images/image-verification-apply-saramin.png
  public/images/image-verification-apply-wanted.png
  public/images/image-verification-nottodo-1.png
  public/images/image-verification-nottodo-2.png
  public/images/image-verification-nottodo-3.png
  public/images/image-verification-nottodo-4.png
  public/images/image-waved-banner1.png
  public/images/image-waved-banner2.png
  public/images/image-waved-banner3.png
  src/components/challenge/ChallengeHeader.tsx
  src/components/challenge/ParticipantButton.tsx
  src/components/challenge/VerificationExample.tsx
  src/components/common/Layout.tsx
  src/components/common/TextArea.tsx
  src/components/home/FloatingBtn.tsx
  src/components/home/HomeHeader.tsx
  src/components/home/ProcessingChallenge.tsx
  src/components/home/ProcessingChallengeCard.tsx
  src/components/home/RecruitingChallengeCard.tsx
  src/components/home/TopBanner.tsx
  src/constants/challengeImagePaths.ts
  src/constants/verificationExamplePaths.ts
  src/lib/axios/home/api.ts
  src/pages/challenge/[groupId].tsx
  src/pages/home/index.tsx
  src/pages/profile/myreview/edit/index.tsx
  src/types/challengeGroup.ts
  src/types/myProcessingChallenge.ts
  src/types/recruitingChallenge.ts
  src/utils/getChallengeImagePath.ts
Labels: ✨ feat, 🔨 refactor

#115 [#106][FEATURE] iOS 스플래시 스크린 적용 & 앱 아이콘 변경
  public/app-assets/logo/128.png
  public/app-assets/logo/144.png
  public/app-assets/logo/192.png
  public/app-assets/logo/48.png
  public/app-assets/logo/512.png
  public/app-assets/logo/72.png
  public/app-assets/logo/96.png
  public/app-assets/splashscreens/iPhone_11_Pro_Max__iPhone_XS_Max_portrait.png
  public/app-assets/splashscreens/iPhone_11__iPhone_XR_portrait.png
  public/app-assets/splashscreens/iPhone_13_mini__iPhone_12_mini__iPhone_11_Pro__iPhone_XS__iPhone_X_portrait.png
  public/app-assets/splashscreens/iPhone_14_Plus__iPhone_13_Pro_Max__iPhone_12_Pro_Max_portrait.png
  public/app-assets/splashscreens/iPhone_14__iPhone_13_Pro__iPhone_13__iPhone_12_Pro__iPhone_12_portrait.png
  public/app-assets/splashscreens/iPhone_15_Pro_Max__iPhone_15_Plus__iPhone_14_Pro_Max_portrait.png
  public/app-assets/splashscreens/iPhone_15_Pro__iPhone_15__iPhone_14_Pro_portrait.png
  public/app-assets/splashscreens/iPhone_8_Plus__iPhone_7_Plus__iPhone_6s_Plus__iPhone_6_Plus_portrait.png
  public/app-assets/splashscreens/iPhone_8__iPhone_7__iPhone_6s__iPhone_6__4.7__iPhone_SE_portrait.png
  public/favicon.ico
  public/manifest.json
  public/manifest/icon_x128.png
  public/manifest/icon_x144.png
  public/manifest/icon_x192.png
  public/manifest/icon_x48.png
  public/manifest/icon_x512.png
  public/manifest/icon_x72.png
  public/manifest/icon_x96.png
  public/next.svg
  public/vercel.svg
  src/components/challenge/ChallengeHeader.tsx
  src/components/common/Layout.tsx
  src/components/home/HomeHeader.tsx
  src/pages/404.tsx
  src/pages/500.tsx
  src/pages/_document.tsx
  src/pages/admin/index.tsx
  src/pages/challenge/participant/success/index.tsx
  src/pages/challenge/request/success/index.tsx
  src/pages/index.tsx
  src/pages/register/index.tsx
  src/pages/register/success/index.tsx
Labels: ✨ feat, ✅ test

#116 [#104][REFACTOR] 마이챌린지,인증내역 페이지 수정사항 반영 및 리팩토링
  public/icons/icon-challenge.svg
  public/icons/icon-mychallenge-completed.svg
  public/icons/icon-mychallenge-waiting.svg
  public/icons/icon-stamp-bad.svg
  public/icons/icon-stamp-default.svg
  public/icons/icon-stamp-good.svg
  public/icons/icon-verification-collection.svg
  public/images/image-emptyview-challenge.png
  public/images/image-emptyview-commit.png
  public/images/image-emptyview-deposit.png
  public/images/image-emptyview-mychallenge-completed.png
  public/images/image-emptyview-mychallenge-waiting.png
  public/images/image-emptyview-mychallenge.png
  public/images/image-emptyview-notification.png
  public/images/image-emptyview-review.png
  public/images/image-emptyview-verification.png
  src/components/common/EmptyView.tsx
  src/components/common/TabMenu.tsx
  src/components/mychallenge/ChallengeEmptyView.tsx
  src/components/mychallenge/ChallengeItem.tsx
  src/components/mychallenge/ChallengeProgress.tsx
  src/components/mychallenge/ChallengeSection.tsx
  src/components/verification/collection/Stamp.tsx
  src/components/verification/collection/VerificationItem.tsx
  src/components/verification/collection/VerificationList.tsx
  src/components/verification/collection/VerificationPhotoItem.tsx
  src/components/verification/post/PhotoInput.tsx
  src/constants/emptyText.ts
  src/constants/emptyViewType.ts
  src/constants/mychallengeStatus.ts
  src/pages/mychallenge/index.tsx
  src/pages/verification/collection/[challengeGroupId].tsx
  src/types/verification.ts
  src/utils/calculateDDay.ts
Labels: 🎨 style, 🔨 refactor

#119 [#114][FEATURE] 서비스 이미지 교체 작업
  public/icons/icon-404-error.svg
  public/icons/icon-500-error.svg
  public/icons/icon-waved-logo.svg
  public/icons/icon-waved-title.svg
  public/images/image-404.svg
  public/images/image-500.svg
  public/images/image-emptyview-myreview.png
  public/images/image-fanfare.svg
  public/images/image-register-success.svg
  public/images/image-waved-preview1.png
  public/images/image-waved-preview2.png
  public/images/image-waved-preview3.png
  src/components/challenge/ChallengeHeader.tsx
  src/components/challenge/ChallengeReview.tsx
  src/components/common/EmptyView.tsx
  src/components/home/HomeHeader.tsx
  src/components/home/RecruitingChallenge.tsx
  src/components/onboarding/PreviewSlider.tsx
  src/constants/emptyViewType.ts
  src/pages/404.tsx
  src/pages/500.tsx
  src/pages/index.tsx
  src/pages/register/success/index.tsx
Labels: 🎨 style

#121 [#117][REFACOTR] 탭메뉴 동작 성능 개선
  src/components/common/TabMenu.tsx
Labels: 🔨 refactor
